// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.3
// source: Reading.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Reading struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Timestamp     string                 `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	DeviceId      string                 `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Co            float64                `protobuf:"fixed64,4,opt,name=co,proto3" json:"co,omitempty"`
	Humidity      float32                `protobuf:"fixed32,5,opt,name=humidity,proto3" json:"humidity,omitempty"`
	Light         bool                   `protobuf:"varint,6,opt,name=light,proto3" json:"light,omitempty"`
	Lpg           float64                `protobuf:"fixed64,7,opt,name=lpg,proto3" json:"lpg,omitempty"`
	Motion        bool                   `protobuf:"varint,8,opt,name=motion,proto3" json:"motion,omitempty"`
	Smoke         float64                `protobuf:"fixed64,9,opt,name=smoke,proto3" json:"smoke,omitempty"`
	Temperature   float32                `protobuf:"fixed32,10,opt,name=temperature,proto3" json:"temperature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reading) Reset() {
	*x = Reading{}
	mi := &file_Reading_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reading) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reading) ProtoMessage() {}

func (x *Reading) ProtoReflect() protoreflect.Message {
	mi := &file_Reading_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reading.ProtoReflect.Descriptor instead.
func (*Reading) Descriptor() ([]byte, []int) {
	return file_Reading_proto_rawDescGZIP(), []int{0}
}

func (x *Reading) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Reading) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *Reading) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *Reading) GetCo() float64 {
	if x != nil {
		return x.Co
	}
	return 0
}

func (x *Reading) GetHumidity() float32 {
	if x != nil {
		return x.Humidity
	}
	return 0
}

func (x *Reading) GetLight() bool {
	if x != nil {
		return x.Light
	}
	return false
}

func (x *Reading) GetLpg() float64 {
	if x != nil {
		return x.Lpg
	}
	return 0
}

func (x *Reading) GetMotion() bool {
	if x != nil {
		return x.Motion
	}
	return false
}

func (x *Reading) GetSmoke() float64 {
	if x != nil {
		return x.Smoke
	}
	return 0
}

func (x *Reading) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

type GetAllReadingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Readings      []*Reading             `protobuf:"bytes,1,rep,name=readings,proto3" json:"readings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllReadingsResponse) Reset() {
	*x = GetAllReadingsResponse{}
	mi := &file_Reading_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllReadingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllReadingsResponse) ProtoMessage() {}

func (x *GetAllReadingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Reading_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllReadingsResponse.ProtoReflect.Descriptor instead.
func (*GetAllReadingsResponse) Descriptor() ([]byte, []int) {
	return file_Reading_proto_rawDescGZIP(), []int{1}
}

func (x *GetAllReadingsResponse) GetReadings() []*Reading {
	if x != nil {
		return x.Readings
	}
	return nil
}

type GetReadingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReadingRequest) Reset() {
	*x = GetReadingRequest{}
	mi := &file_Reading_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReadingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReadingRequest) ProtoMessage() {}

func (x *GetReadingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Reading_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReadingRequest.ProtoReflect.Descriptor instead.
func (*GetReadingRequest) Descriptor() ([]byte, []int) {
	return file_Reading_proto_rawDescGZIP(), []int{2}
}

func (x *GetReadingRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CreateReadingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reading       *Reading               `protobuf:"bytes,1,opt,name=reading,proto3" json:"reading,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReadingRequest) Reset() {
	*x = CreateReadingRequest{}
	mi := &file_Reading_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReadingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReadingRequest) ProtoMessage() {}

func (x *CreateReadingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Reading_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReadingRequest.ProtoReflect.Descriptor instead.
func (*CreateReadingRequest) Descriptor() ([]byte, []int) {
	return file_Reading_proto_rawDescGZIP(), []int{3}
}

func (x *CreateReadingRequest) GetReading() *Reading {
	if x != nil {
		return x.Reading
	}
	return nil
}

type CreateReadingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReadingResponse) Reset() {
	*x = CreateReadingResponse{}
	mi := &file_Reading_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReadingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReadingResponse) ProtoMessage() {}

func (x *CreateReadingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Reading_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReadingResponse.ProtoReflect.Descriptor instead.
func (*CreateReadingResponse) Descriptor() ([]byte, []int) {
	return file_Reading_proto_rawDescGZIP(), []int{4}
}

func (x *CreateReadingResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type RemoveReadingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveReadingRequest) Reset() {
	*x = RemoveReadingRequest{}
	mi := &file_Reading_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveReadingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveReadingRequest) ProtoMessage() {}

func (x *RemoveReadingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Reading_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveReadingRequest.ProtoReflect.Descriptor instead.
func (*RemoveReadingRequest) Descriptor() ([]byte, []int) {
	return file_Reading_proto_rawDescGZIP(), []int{5}
}

func (x *RemoveReadingRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateReadingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Reading       *Reading               `protobuf:"bytes,2,opt,name=reading,proto3" json:"reading,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateReadingRequest) Reset() {
	*x = UpdateReadingRequest{}
	mi := &file_Reading_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateReadingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReadingRequest) ProtoMessage() {}

func (x *UpdateReadingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Reading_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReadingRequest.ProtoReflect.Descriptor instead.
func (*UpdateReadingRequest) Descriptor() ([]byte, []int) {
	return file_Reading_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateReadingRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateReadingRequest) GetReading() *Reading {
	if x != nil {
		return x.Reading
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_Reading_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_Reading_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_Reading_proto_rawDescGZIP(), []int{7}
}

var File_Reading_proto protoreflect.FileDescriptor

const file_Reading_proto_rawDesc = "" +
	"\n" +
	"\rReading.proto\"\xf8\x01\n" +
	"\aReading\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\tR\ttimestamp\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\tR\bdeviceId\x12\x0e\n" +
	"\x02co\x18\x04 \x01(\x01R\x02co\x12\x1a\n" +
	"\bhumidity\x18\x05 \x01(\x02R\bhumidity\x12\x14\n" +
	"\x05light\x18\x06 \x01(\bR\x05light\x12\x10\n" +
	"\x03lpg\x18\a \x01(\x01R\x03lpg\x12\x16\n" +
	"\x06motion\x18\b \x01(\bR\x06motion\x12\x14\n" +
	"\x05smoke\x18\t \x01(\x01R\x05smoke\x12 \n" +
	"\vtemperature\x18\n" +
	" \x01(\x02R\vtemperature\">\n" +
	"\x16GetAllReadingsResponse\x12$\n" +
	"\breadings\x18\x01 \x03(\v2\b.ReadingR\breadings\"#\n" +
	"\x11GetReadingRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\":\n" +
	"\x14CreateReadingRequest\x12\"\n" +
	"\areading\x18\x01 \x01(\v2\b.ReadingR\areading\"'\n" +
	"\x15CreateReadingResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"&\n" +
	"\x14RemoveReadingRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"J\n" +
	"\x14UpdateReadingRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\"\n" +
	"\areading\x18\x02 \x01(\v2\b.ReadingR\areading\"\a\n" +
	"\x05Empty2\x99\x02\n" +
	"\x0eReadingService\x123\n" +
	"\x0eGetAllReadings\x12\x06.Empty\x1a\x17.GetAllReadingsResponse\"\x00\x12,\n" +
	"\n" +
	"GetReading\x12\x12.GetReadingRequest\x1a\b.Reading\"\x00\x12@\n" +
	"\rCreateReading\x12\x15.CreateReadingRequest\x1a\x16.CreateReadingResponse\"\x00\x120\n" +
	"\rRemoveReading\x12\x15.RemoveReadingRequest\x1a\x06.Empty\"\x00\x120\n" +
	"\rUpdateReading\x12\x15.UpdateReadingRequest\x1a\x06.Empty\"\x00B\x06Z\x04./pbb\x06proto3"

var (
	file_Reading_proto_rawDescOnce sync.Once
	file_Reading_proto_rawDescData []byte
)

func file_Reading_proto_rawDescGZIP() []byte {
	file_Reading_proto_rawDescOnce.Do(func() {
		file_Reading_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Reading_proto_rawDesc), len(file_Reading_proto_rawDesc)))
	})
	return file_Reading_proto_rawDescData
}

var file_Reading_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_Reading_proto_goTypes = []any{
	(*Reading)(nil),                // 0: Reading
	(*GetAllReadingsResponse)(nil), // 1: GetAllReadingsResponse
	(*GetReadingRequest)(nil),      // 2: GetReadingRequest
	(*CreateReadingRequest)(nil),   // 3: CreateReadingRequest
	(*CreateReadingResponse)(nil),  // 4: CreateReadingResponse
	(*RemoveReadingRequest)(nil),   // 5: RemoveReadingRequest
	(*UpdateReadingRequest)(nil),   // 6: UpdateReadingRequest
	(*Empty)(nil),                  // 7: Empty
}
var file_Reading_proto_depIdxs = []int32{
	0, // 0: GetAllReadingsResponse.readings:type_name -> Reading
	0, // 1: CreateReadingRequest.reading:type_name -> Reading
	0, // 2: UpdateReadingRequest.reading:type_name -> Reading
	7, // 3: ReadingService.GetAllReadings:input_type -> Empty
	2, // 4: ReadingService.GetReading:input_type -> GetReadingRequest
	3, // 5: ReadingService.CreateReading:input_type -> CreateReadingRequest
	5, // 6: ReadingService.RemoveReading:input_type -> RemoveReadingRequest
	6, // 7: ReadingService.UpdateReading:input_type -> UpdateReadingRequest
	1, // 8: ReadingService.GetAllReadings:output_type -> GetAllReadingsResponse
	0, // 9: ReadingService.GetReading:output_type -> Reading
	4, // 10: ReadingService.CreateReading:output_type -> CreateReadingResponse
	7, // 11: ReadingService.RemoveReading:output_type -> Empty
	7, // 12: ReadingService.UpdateReading:output_type -> Empty
	8, // [8:13] is the sub-list for method output_type
	3, // [3:8] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_Reading_proto_init() }
func file_Reading_proto_init() {
	if File_Reading_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Reading_proto_rawDesc), len(file_Reading_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Reading_proto_goTypes,
		DependencyIndexes: file_Reading_proto_depIdxs,
		MessageInfos:      file_Reading_proto_msgTypes,
	}.Build()
	File_Reading_proto = out.File
	file_Reading_proto_goTypes = nil
	file_Reading_proto_depIdxs = nil
}
