// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.3
// source: Reading.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ReadingService_GetAllReadings_FullMethodName = "/ReadingService/GetAllReadings"
	ReadingService_GetReading_FullMethodName     = "/ReadingService/GetReading"
	ReadingService_AddReading_FullMethodName     = "/ReadingService/AddReading"
	ReadingService_RemoveReading_FullMethodName  = "/ReadingService/RemoveReading"
	ReadingService_UpdateReading_FullMethodName  = "/ReadingService/UpdateReading"
)

// ReadingServiceClient is the client API for ReadingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReadingServiceClient interface {
	GetAllReadings(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetAllReadingsResponse, error)
	GetReading(ctx context.Context, in *GetReadingRequest, opts ...grpc.CallOption) (*Reading, error)
	AddReading(ctx context.Context, in *AddReadingRequest, opts ...grpc.CallOption) (*Empty, error)
	RemoveReading(ctx context.Context, in *RemoveReadingRequest, opts ...grpc.CallOption) (*Empty, error)
	UpdateReading(ctx context.Context, in *UpdateReadingRequest, opts ...grpc.CallOption) (*Empty, error)
}

type readingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewReadingServiceClient(cc grpc.ClientConnInterface) ReadingServiceClient {
	return &readingServiceClient{cc}
}

func (c *readingServiceClient) GetAllReadings(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetAllReadingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllReadingsResponse)
	err := c.cc.Invoke(ctx, ReadingService_GetAllReadings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *readingServiceClient) GetReading(ctx context.Context, in *GetReadingRequest, opts ...grpc.CallOption) (*Reading, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Reading)
	err := c.cc.Invoke(ctx, ReadingService_GetReading_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *readingServiceClient) AddReading(ctx context.Context, in *AddReadingRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ReadingService_AddReading_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *readingServiceClient) RemoveReading(ctx context.Context, in *RemoveReadingRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ReadingService_RemoveReading_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *readingServiceClient) UpdateReading(ctx context.Context, in *UpdateReadingRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ReadingService_UpdateReading_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReadingServiceServer is the server API for ReadingService service.
// All implementations must embed UnimplementedReadingServiceServer
// for forward compatibility.
type ReadingServiceServer interface {
	GetAllReadings(context.Context, *Empty) (*GetAllReadingsResponse, error)
	GetReading(context.Context, *GetReadingRequest) (*Reading, error)
	AddReading(context.Context, *AddReadingRequest) (*Empty, error)
	RemoveReading(context.Context, *RemoveReadingRequest) (*Empty, error)
	UpdateReading(context.Context, *UpdateReadingRequest) (*Empty, error)
	mustEmbedUnimplementedReadingServiceServer()
}

// UnimplementedReadingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReadingServiceServer struct{}

func (UnimplementedReadingServiceServer) GetAllReadings(context.Context, *Empty) (*GetAllReadingsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllReadings not implemented")
}
func (UnimplementedReadingServiceServer) GetReading(context.Context, *GetReadingRequest) (*Reading, error) {
	return nil, status.Error(codes.Unimplemented, "method GetReading not implemented")
}
func (UnimplementedReadingServiceServer) AddReading(context.Context, *AddReadingRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method AddReading not implemented")
}
func (UnimplementedReadingServiceServer) RemoveReading(context.Context, *RemoveReadingRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveReading not implemented")
}
func (UnimplementedReadingServiceServer) UpdateReading(context.Context, *UpdateReadingRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateReading not implemented")
}
func (UnimplementedReadingServiceServer) mustEmbedUnimplementedReadingServiceServer() {}
func (UnimplementedReadingServiceServer) testEmbeddedByValue()                        {}

// UnsafeReadingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReadingServiceServer will
// result in compilation errors.
type UnsafeReadingServiceServer interface {
	mustEmbedUnimplementedReadingServiceServer()
}

func RegisterReadingServiceServer(s grpc.ServiceRegistrar, srv ReadingServiceServer) {
	// If the following call panics, it indicates UnimplementedReadingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ReadingService_ServiceDesc, srv)
}

func _ReadingService_GetAllReadings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReadingServiceServer).GetAllReadings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReadingService_GetAllReadings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReadingServiceServer).GetAllReadings(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReadingService_GetReading_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReadingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReadingServiceServer).GetReading(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReadingService_GetReading_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReadingServiceServer).GetReading(ctx, req.(*GetReadingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReadingService_AddReading_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddReadingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReadingServiceServer).AddReading(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReadingService_AddReading_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReadingServiceServer).AddReading(ctx, req.(*AddReadingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReadingService_RemoveReading_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveReadingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReadingServiceServer).RemoveReading(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReadingService_RemoveReading_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReadingServiceServer).RemoveReading(ctx, req.(*RemoveReadingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReadingService_UpdateReading_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateReadingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReadingServiceServer).UpdateReading(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReadingService_UpdateReading_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReadingServiceServer).UpdateReading(ctx, req.(*UpdateReadingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ReadingService_ServiceDesc is the grpc.ServiceDesc for ReadingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReadingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ReadingService",
	HandlerType: (*ReadingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllReadings",
			Handler:    _ReadingService_GetAllReadings_Handler,
		},
		{
			MethodName: "GetReading",
			Handler:    _ReadingService_GetReading_Handler,
		},
		{
			MethodName: "AddReading",
			Handler:    _ReadingService_AddReading_Handler,
		},
		{
			MethodName: "RemoveReading",
			Handler:    _ReadingService_RemoveReading_Handler,
		},
		{
			MethodName: "UpdateReading",
			Handler:    _ReadingService_UpdateReading_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Reading.proto",
}
