name: "Project 3"
services:
  postgres:
    image: postgres:16
    container_name: postgres-3
    environment:
      POSTGRES_USER: matija
      POSTGRES_PASSWORD: matija
      POSTGRES_DB: iotdb
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - iot-net-3
      
  datamanager:
    build: ./DataManager
    container_name: datamanager-3
    ports:
      - "8081:8080"
    environment:
       POSTGRES_URL: "postgres://matija:matija@postgres:5432/iotdb?sslmode=disable"
    networks:
      - iot-net-3
    depends_on:
      - postgres

  gateway:
    build: ./Gateway
    container_name: gateway-3
    platform: "linux/amd64"
    ports:
      - "5237:5236"
    environment:
      DATAMANAGER_HOST: "datamanager:8080"
    networks:
      - iot-net-3
    depends_on:
      - datamanager

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto-3
    ports:
      - "1884:1883"
      - "9002:9001"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    networks:
      - iot-net-3

  eventmanager:
    build: ./EventManager
    container_name: eventmanager-3
    ports:
      - "8091:8090"
    networks:
      - iot-net-3
    depends_on:
      - mosquitto

  mqtt-nats-client:
      build: ./mqtt-client
      container_name: mqtt-client-3
      ports:
        - "3001:3000"
      environment:
        - NODE_ENV=production
      networks:
        - iot-net-3
      depends_on:
        - mosquitto

  sensor-generator:
    build: ./SensorGenerator
    container_name: sensor-generator-3
    stdin_open: true  
    tty: true      
    networks:
      - iot-net-3
    depends_on:
      - gateway
    
  mlaas:
    build: ./MLaaS
    container_name: mlaas-3
    ports:
      - "8101:8100"
    networks:
      - iot-net-3

  nats:
    container_name: nats-3
    image: nats:latest
    ports: 
      - "8223:8222"
      - "4223:4222"
    networks: 
      - iot-net-3

  analytics:
    build: 
      context: ./Analytics
      args:
        TARGETPLATFORM: linux/arm64  
    container_name: analytics-3
    ports:
      - "8111:8110"
    networks:
      - iot-net-3
    depends_on:
      - nats
      - mlaas
      - mosquitto
      
networks:
  iot-net-3:
    driver: bridge

volumes:
  pgdata:
    driver: local
  mosquitto_data:
    driver: local
  mosquitto_log:
    driver: local
    