name: "Project 1"
services:
  postgres:
    image: postgres:16
    container_name: postgres-1
    environment:
      POSTGRES_USER: matija
      POSTGRES_PASSWORD: matija
      POSTGRES_DB: iotdb
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - iot-net-1
  datamanager:
    build: ./DataManager
    container_name: datamanager-1
    ports:
      - "8081:8080"
    environment:
       POSTGRES_URL: "postgres://matija:matija@postgres:5432/iotdb?sslmode=disable"
    networks:
      - iot-net-1
    depends_on:
      - postgres
  gateway:
    build: ./Gateway
    container_name: gateway-1
    platform: "linux/amd64"
    ports:
      - "5237:5236"
    environment:
      DATAMANAGER_HOST: "datamanager:8080"
    networks:
      - iot-net-1
    depends_on:
      - datamanager

networks:
  iot-net-1:
    driver: bridge

volumes:
  pgdata:
    driver: local
    